services:
  main:
    build: ./task_tracker
    ports: 
      - '3000:3000'
    volumes:
      - ./task_tracker:/usr/src/async_architecture
    tty: true
    stdin_open: true

  auth:
    build: ./auth
    ports: 
      - '3001:3000'
    volumes:
      - ./auth:/usr/src/async_architecture
    tty: true
    stdin_open: true
  #    environment:
#      RAILS_ENV: production

  postgres:
    image: postgres:10
    environment: 
      POSTGRES_PASSWORD: 123
    volumes:
      - ./arch_db:/var/lib/postgresql/data